mock_fb_app: &FAKE
  app_id: 102222349832093
  secret: 918cd2bddf254fbbfab4b5c1666f7667

development:
  <<: *FAKE

test:
  <<: *FAKE

cucumber:
  <<: *FAKE

staging:
  app_id: 138436116175329
  secret: 4448edef8ad7b1bdb52c7a184d292989

production:
  app_id: 147177445296317
  secret: 7b651e84a6eb8a5824913467c569aaac